# Generated by Django 3.1.4 on 2021-01-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('ci', models.TimeField(verbose_name='check in')),
                ('co', models.TimeField(verbose_name='check out')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
